"""
YOLOv5 v5.0 及以下版本策略

训练参数传递方式：
  - 通过 hyp.yaml 文件传递超参（优化器 + 数据增强）
  - 通过命令行标志控制功能开关（multi-scale, rect, label-smoothing, adam）
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from .base import VersionStrategy

logger = logging.getLogger(__name__)


class V5Strategy(VersionStrategy):
    """v5.0 及以下版本策略"""

    def build_command(
        self,
        config,
        yolov5_path: Path,
        weights_path: Optional[str],
    ) -> list[str]:
        cmd = self._build_base_command(config, yolov5_path, weights_path)

        # hyp 文件
        hyp_file = self._create_hyp_file(config, yolov5_path)
        if hyp_file:
            cmd.extend(['--hyp', str(hyp_file)])

        cmd.append('--cache-images')

        if config.TRAINING.get('multi_scale', False):
            cmd.append('--multi-scale')
        if config.TRAINING.get('rect', False):
            cmd.append('--rect')
        ls = config.TRAINING.get('label_smoothing', 0.0)
        if ls > 0:
            cmd.extend(['--label-smoothing', str(ls)])
        if config.OPTIMIZER.get('use_adam', False):
            cmd.append('--adam')

        logger.info(f"YOLOv5 v{config.YOLO_VERSION}：使用 hyp.yaml + 标志参数配置训练")
        return cmd

    # ==================== hyp 文件管理 ====================

    def _create_hyp_file(self, config, yolov5_path: Path) -> Optional[Path]:
        """创建或定位 hyp 文件"""
        default_hyp = yolov5_path / "data" / "hyp.scratch.yaml"
        if default_hyp.exists():
            logger.info(f"使用 YOLOv5 默认 hyp 文件: {default_hyp}")
            return default_hyp

        hyp_file = config.PATHS['project_dir'] / 'hyp.custom.yaml'
        hyp_file.parent.mkdir(parents=True, exist_ok=True)
        with open(hyp_file, 'w', encoding='utf-8') as f:
            f.write(self._generate_hyp_yaml_content(config))
        logger.info(f"创建自定义 hyp 文件: {hyp_file}")
        return hyp_file

    @staticmethod
    def _generate_hyp_yaml_content(config) -> str:
        """生成 v5.0 兼容的 hyp.yaml 内容（动态从配置字典生成）"""
        lines = ["# YOLOv5 Hyperparameters (generated by config)"]
        lines.append("")
        lines.append("# Optimizer")
        for key, value in config.OPTIMIZER.items():
            lines.append(f"{key}: {value}")
        lines.append("")
        lines.append("# Augmentation")
        for key, value in config.AUGMENTATION.items():
            lines.append(f"{key}: {value}")
        lines.append("")
        lines.append("# Loss (fixed values)")
        for key, value in [
            ("box", 0.05), ("cls", 0.5), ("cls_pw", 1.0),
            ("obj", 1.0), ("obj_pw", 1.0), ("iou_t", 0.20),
            ("anchor_t", 4.0), ("fl_gamma", 0.0),
        ]:
            lines.append(f"{key}: {value}")
        return "\n".join(lines) + "\n"
